docker push mercureimaging/mercure-router:latest
docker push mercureimaging/mercure-processor:latest
docker push mercureimaging/mercure-receiver:latest
docker push mercureimaging/mercure-dispatcher:latest
docker push mercureimaging/mercure-bookkeeper:latest
docker push mercureimaging/mercure-cleaner:latest
docker push mercureimaging/mercure-ui:latest
docker push mercureimaging/alpine-sshd:latest
docker push mercureimaging/processing-step:latest
docker push mercureimaging/mercure-dummy-processor:latest
