"""tasks tracking

Revision ID: ee4575e2cf40
Revises: 57724e1ea282
Create Date: 2022-02-24 20:11:56.419148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee4575e2cf40'
down_revision = '57724e1ea282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('series_uid', sa.String(), nullable=True),
    sa.Column('study_uid', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dicom_series', sa.Column('study_uid', sa.String(), nullable=True))
    op.add_column('series_events', sa.Column('task_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'series_events', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series_events', type_='foreignkey') # type: ignore
    op.drop_column('series_events', 'task_id')
    op.drop_column('dicom_series', 'study_uid')
    op.drop_table('tasks')
    # ### end Alembic commands ###
