[Service]
InaccessiblePaths=/opt/mercure/config/webgui.env
InaccessiblePaths=/opt/mercure/config/bookkeeper.env
InaccessiblePaths=/opt/mercure/config/redis.env
InaccessiblePaths=/opt/mercure/config/db.env
